browser: false
sources:
  - name: Github
    handler:
      graphql:
        endpoint: https://api.github.com/graphql
  - name: Orbit
    handler:
      openapi:
        source: https://app.orbit.love/api-docs/v1/swagger.json